name: Node.js CI con Jest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Dar permisos a Jest
        run: chmod +x ./node_modules/.bin/jest

      - name: Ejecutar pruebas
        run: npm test
